on: push
name: aws_eks_kubeflow
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build . --file Dockerfile --tag pulumi-k8s-kubeflow:$(date +%s)
    - name: Deploy
      id: deploy
      uses: docker://ramene/actions:alpha
      env:
        PULUMI_CI: up
        PULUMI_ROOT: infra
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      with:
        args: up
    - name: EKS Node Authentication  # FIX: Here we're no longer using our simple action, we're now switching over to using our customized AWS Action container
      id: kubectl
      uses: docker://ramene/actions-kubectl # TODO: need to confirm my assumptions here., previously: `ramene/aws/kubectl@master`
      with:
        args: get pods --all-namespaces # TODO: eventually support if we're using kustomize, use `-k`