on: push
name: aws_eks_kubeflow
jobs:
  build:
    name: Orchestration
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v1
    - name: Build
      run: docker build . --file Dockerfile --tag pulumi-k8s-kubeflow:$(date +%s)
    - name: Cluster Lifecycle
      id: deploy
      uses: docker://ramene/actions:alpha
      env:
        PULUMI_CI: up
        PULUMI_ROOT: infra
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      with:
        args: up
    - name: Worker Node Group Authorization
      id: kubectl
      uses: docker://ramene/actions-kubectl:v0.0.1 # TODO(@question): Can the whole of the build hold ENV vars?.  I don't like having to pass the env under the same job.
      with:
        args: get cluster-info
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  kubeflow:
    name: Deploy Kubeflow
    runs-on: ubuntu-latest
    steps:
    - name: CRD
      id: message
      uses: ramene/simple-echo-action@master
      with:
        broadcast: "broadcast message"
        some_var: "some_var value defined in workflow"
    - name: Broadcast time
      run: echo "The time was ${{ steps.message.outputs.time }}"
    - name: Pulumi
      run: echo "Outputs - ${{ steps.message.outputs.foo }}"