on: pull_request
name: Preview
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: docker://alpine
      with:
        entrypoint: app/build
    - name: Pulumi Preview (Merged Stack)
      uses: docker://pulumi/actions
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: pr
      with:
        args: preview